### ISSUE TITLE
Create initial risk event detectors

### ISSUE THREAD

**Issue by msmarioo** [eclipse-sdv-blueprints/insurance#7]
Create initial detectors. The detectors should have

- A basic detector (e.g. crash signal)
- A detector that requires a series of events (e.g. turn signal indicator must be active < 500 ms after detecting a turn)

**Comment by nacidai** [comment]
@msmarioo  PR is merged.  if you want me to close this issue, please comment here

**Comment by msmarioo** [comment]
This issue can be closed. We have a good collection of initial risk detector events
